version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
      - npm install -g knex
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install .
      - chmod +x migrate.sh
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - ./migrate.sh
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./report.json
